### ISSUE TITLE
Clear Input

### ISSUE THREAD

**Issue by hari7priya** [nshaposhnik/React-Native-Virtual-Keyboard#11]
How to clear input in the library? 

1. this.state.text="" on load. 
2. onPress={(Input) =>   this.setState({ text })} //Input=123 and this.state.text=123
3. onClick of Submit, this.state.text="" 

click on any key on keypad, Input is still = 123.
How to reset Input value?

**Comment by nshaposhnik** [comment]
Use pressMode prop equal to 'char' (instead of default 'string'), this way each individual symbol is passed instead of the whole string, and you have direct control over what to do.

**Comment by hari7priya** [comment]
Thank you for the reply.

onPress 'char' backspace is returning 'back' string instead of clearing the character. 
I made to work the following way, just in case if anyone else wants --

   <VirtualKeyboard
                  color="black"
                  pressMode="char"
                  cellStyle={styles.numberButton} //custom styling for each cell
                  applyBackspaceTint={true}
                  onPress={(inputCharacter) => {
                    var id = this.state.text;
                    if (inputCharacter == "back") {
                      if (this.state.text == "") return;
                      else {
                        this.setState({
                          text: id.substring(0, id.length - 1),
                        });
                      }
                    } else {
                      this.setState({ text: id + inputCharacter });
                    }
                  }}
                />
              </View>
