### ISSUE TITLE
VirtualKeyboard.style' does not contain a default export (imported as 'styles').

### ISSUE THREAD

**Issue by huzaifah050** [nshaposhnik/React-Native-Virtual-Keyboard#14]
After installing the package, a simple import as this generates this error:

node_modules/react-native-virtual-keyboard/src/VirtualKeyboard.js
Attempted import error: './VirtualKeyboard.style' does not contain a default export (imported as 'styles').

```js
import React from 'react';
import { View, Text } from 'react-native';
import VirtualKeyboard from 'react-native-virtual-keyboard';

const Test = () => {
	return (
		<View>
		  <Text>Testing</Text>
		</View>
	);
};

export default Test;

```

**Comment by Maker-Mark** [comment]
This issue still exists...

**Comment by nshaposhnik** [comment]
did not reproduce, but might be fixed with the new version.
