### ISSUE TITLE
Reset value upon form submission

### ISSUE THREAD

**Issue by RayBans2111** [nshaposhnik/React-Native-Virtual-Keyboard#15]
Hello,

I have been having this issue where I am utilizing this library in order to achieve a nice login page for my app. I have an issue where when I submit my 'credential' using the number pad from this library, the original credential will reappear upon trying a new login again. 

I read up on this thread where the OP was also having this issue appear in his app, but I found the answer to be a bit unclear, coming from a beginner dev. https://github.com/nshaposhnik/React-Native-Virtual-Keyboard/issues/2#issuecomment-347210987

Would you mind elaborating on what I would need to do in order to keep the old credential string from appearing? I have included screenshots below. Let me know if you need anything else from me. 

![myLogin](https://user-images.githubusercontent.com/77131939/110864670-0b333300-8288-11eb-8558-03a5941098d7.jpg)

``` 
function LoginForm() {
  const { t } = useTranslation() 
  const nav = useNavigation()
  const formikRef = useRef<any>()

  useEffect(() => {
    const reset = nav.addListener('focus', () => {
      formikRef.current.resetForm()
      formikRef.current.values.phoneCredential = ''
      console.log('reset fired')
      console.log(formikRef.current.values)
    })
    return reset
  }, [nav])

  return (
    <View style={[globalStyles.container, { justifyContent: 'space-between' }]}>
      <View>
        <Text style={globalStyles.pageTitle}>{t('personSelect.welcome')}</Text>
        <Text style={globalStyles.generalText}>{t('login.signIn')}</Text>
      </View>

      <Formik
        innerRef={formikRef}
        initialValues={{ phoneCredential: '' }}
        onSubmit={(values: any, props) => {
          console.log('phone: ' + values.phoneCredential)
          nav.navigate('PersonSelect')
        }}
      >
        {(props: any) =>
          <View style={styles.userInputContainer}>
            <View style={styles.phonePadContainer}>
              <TextInputMask 
                type={'custom'}
                options={{ mask: '(999) 999-9999' }}
                value={props.values.phoneCredential}
                editable={false}
                placeholder={SCREEN_WIDTH > 425 ? "(xxx)  xxx  xxxx" : undefined}
                style={styles.phoneNumberField}
              />
              <VirtualKeyboard
                pressMode='string' 
                onPress={props.handleChange('phoneCredential')}
                color='#7484E7'
                rowStyle={{ marginTop: 6 }}
                cellStyle={styles.phonepadCell}
                style={{ marginBottom: ActuatedSize(12) }}
              />
            </View>

            <View>
              <ASimpleBtn 
                disabled={props.values && props.values.phoneCredential.length != 10 ? true : false}
                onPress={props.submitForm}
                btnText={t('login.login')}
              />           
            </View>
          </View>
        }
      </Formik>
    </View>
  )
}

**Comment by nshaposhnik** [comment]
You see, when you use `pressMode='string'`, you don't have any control over the string inside VirtualKeyboard. In your case, if you assign empty string to `phoneCredential ` in your local state, that updates string only in your local state, it's not influencing string in VirtualKeyboard in any way. Thus, my answer will be same as in the issue you've mentioned, if you want more control, please use `pressMode='char'`, then each individual symbol pressed on keyboard will be passed to `onPress`, and you're free to reset string in your local state as you want.
