### ISSUE TITLE
clear input possibility

### ISSUE THREAD

**Issue by freemanUA** [nshaposhnik/React-Native-Virtual-Keyboard#2]
Hi, 
I storing entered pin in redux store and if pin is wrong I clearing this prop by setting it to "", but when user is trying to re-enter the pin, old pin is still there. How to clear the input?

some similar issues:
https://stackoverflow.com/questions/45249807/clear-react-native-textinput

**Comment by nshaposhnik** [comment]
If you want to clear the string, you need to use this library with pressMode='char' prop. What happens now is that you clear the string inside of your app, but it doesn't clears string which is formed inside the library.
