### ISSUE TITLE
Undefined is not an object

### ISSUE THREAD

**Issue by amingomezd** [nshaposhnik/React-Native-Virtual-Keyboard#3]
Hi, i have a fresh install of react-native, copy paste your example code and have this error pointing to the source file: 

<img width="259" alt="captura de pantalla 2018-02-13 a la s 6 12 41 p m" src="https://user-images.githubusercontent.com/24884401/36179223-8389f604-10e9-11e8-8aae-ac2e97528217.png">

<img width="694" alt="captura de pantalla 2018-02-13 a la s 6 13 09 p m" src="https://user-images.githubusercontent.com/24884401/36179247-95b85f64-10e9-11e8-9ddb-2252a0daeb08.png">

can you please help me with this issue?

**Comment by FIRAT-URASLI** [comment]
Did you try restart npm server with "npm start --reset-cache"  ?

**Comment by veb** [comment]
I had a very similar issue so I installed `prop-types` and in `VirtualKeyboard.js` removed `React` from all the PropTypes like:

```
	static propTypes = {
		pressMode: PropTypes.oneOf(['string', 'char']),
		color: PropTypes.string,
		onPress: PropTypes.func.isRequired,
		backspaceImg: PropTypes.number,
		applyBackspaceTint: PropTypes.bool,
		decimal: PropTypes.bool,
	}
```

Hope this helps someone else. 👍 my problem, I believe was the later versions of React have removed PropTypes or something.
